### PR TITLE
Fixed the behavior of scrollsToTop that owned by a original window.

### PR DESCRIPTION
**Pull request by atty303**

### CODE REVIEW

**Comment by domesticcatsoftware** [comment]
I'm not sure what this fixes, the text shouldn't get long enough to scroll I wouldn't think?

**Comment by atty303** [comment]
You can see this behavior in DCIntrospectDemo application.
This application has only one UITableView. I was expected to work it's scroll-to-top gesture. It doesn't work because DCIntrospect inject another UIScrollView to UIWindow.
If apply this patch, demo application's scroll-to-top gesture to work.

Quote from the reference of scrollsToTop:

> The scroll-to-top gesture is a tap on the status bar; when this property is YES, the scroll view jumps to the top of the content when this gesture occurs. The default value of this property is YES.
> This gesture works on a single visible scroll view; if there are multiple scroll views (for example, a date picker) with this property set, or if the delegate returns NO in scrollViewWillScrollToTop:, UIScrollView ignores the request.

**Comment by 0xced** [comment]
When I changed from `UITextField` to `UITextView` in 80425e50bb in order to support arrow keys I did not realize that I was adding a `UIScrollView` so that's probably the right thing do.

The text contains two newlines so yes, it will probably scroll.

**Comment by myell0w** [comment]
+1, scrollsTopTop doesn't work anymore when DCIntrospect is activated. Just wasted more than an hour searching for the solution until I realized DCintrospect is to blame :)

**Comment by domesticcatsoftware** [comment]
Aha, that makes sense.  My bad myell0w, I owe you an hour!

**Comment by myell0w** [comment]
well you saved my more than an hour by writing this awesome library, so we are good I guess ;)

Am 11.10.2011 um 23:05 schrieb Patrick Richards:

**Pull request merged**
